[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
newtoken = "9Ysp3neWorju2ngDVKRfa7FpoR1dy6fSX44rJECXKaxX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/empiric-u3/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
