[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
newtoken = "7SWQTWv4NAAN53zidepsVPYEAAdK7kuSGM83m6NsnGw8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/empiric-u3/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
